### PR TITLE
feat: trpc 11

### PR DESCRIPTION
**Pull request by yovanoc**
I upgraded the code to work with trpc 11.

fixed some uws invalid response access error too but as stated in my other PR #4 I know you are scared about changing the way the ws adapter given by the trpc team but I swear this is tested and better. 

the actual state of this PR is deployed at `trpc-uwebsockets-next` and I will soon update with my uws-ish version if you want to test.

Moreover, with the actual state we can't set headers in the context while upgrading WS if we are staying with this version.

### CODE REVIEW

**Comment by romanzy313** [comment]
Thanks for the PR. I will review the changes in a bit. I dont understand the last part. The issue of unable to set headers with the [responseMeta](https://trpc.io/docs/server/caching)? The unit tests show that it works.

And I'm totally fine with changing the implementation, but in my opinion it would be better for long-term upgradability to keep it sync with other adapters. As long as the tests pass, and it makes the library better, I'm totally on board with changes.

Cheers!

**Comment by yovanoc** [comment]
Yes, I agree with you but as trpc themselves said this is kinda rough I think we could write this adapter more like the uws way.

But there is no responseMeta with the applyWSHandler, my need is to set cookie and/or rate limiter response while upgrading to the websocket too

**Comment by romanzy313** [comment]
I don't think it's a good idea to do anything rather then upgrade the connection. The initial request is to negotiate upgrade to websocket with 101 response.

I am not aware of any ws implementation that allows to set cookies, as it's outside of the websocket protocol.

This is why the browser does not allow sending custom headers with the request and does now allow see response headers. It only sends the cookies.

You can accomplish what you need with a separate http request.

**Comment by yovanoc** [comment]
Sending headers back in the upgrade is a common things supported by all WebSocket servers. 
It is a different thing than changing headers in the client, of course it shows response headers

Screenshot 2024-01-19 at 23 23 50

**Comment by romanzy313** [comment]
But you are unable to read these response headers in javascript.

This is out of spec. Why implement features which are not implemented anywhere else. The solution to your problem is do a separate http request.

**Comment by yovanoc** [comment]
I don't want to read it with javascript. I just want to add to this library a feature that have all websockets server out there, but no problem, I think I have to start a separate repository

**Comment by romanzy313** [comment]
Can you please explain why sending cookies is needed during the upgrade? 

Implementing features just to have them is not sustainable. Keeping technical complexity low is more important. Also, why implement something that can be done in a simpler way, via an http request.
I have also dealt with cookies before and it can be a pain to work with. Properly sending multiple cookies takes a lot of effort and is very error prone.

**Comment by yovanoc** [comment]
For example, my clients need to know their rate limiting state. I agree with you for the complexity part, but a client shouldn't send more requests to know their limits. Its not that hard too, the createContext just need to be in the upgrade part. that way the context handler can send headers. I already have all of these in production but I was thinking more people could benefits from this. I tested in my staging environment to replace my adapter to this lib and everything was falling apart, I thought it could be good to contribute, but I will start my version aside, and will link to you to have a look if you want.

**Comment by romanzy313** [comment]
I have added these changes, they are now at  `feat/v11` branch. The code works, but it uses v10 deprivated apis. Namely:
```js
import {
  AnyRouter,
  callProcedure,
  getErrorShape,
} from '@trpc/server';
```

I've marked them with comment `// FIXME depricated`

Also this import does not look nice:
```js
import type { MaybePromise } from '@trpc/server/dist/@trpc-core-unstable-do-not-import-this-please';
```

You can use the beta version via `npm install trpc-uwebsockets@beta`

**Comment by yovanoc** [comment]
Yes, totally agree, but they are still using this for their adapters too, maybe we have to wait more for this

**Comment by yovanoc** [comment]
Btw, I see another issue, you register 2 onAborted callback and uws only trigger one https://github.com/romanzy313/trpc-uwebsockets/blob/1245dad9b0942ff4a2d86a2dc09d8136411aeec1/src/utils.ts#L59 , I added the aborted = true on this one and totally remove the other to not have crash on production

**Pull request closed without merging**
