### PR TITLE
feat: production ready

### PR DESCRIPTION
**Pull request by yovanoc**
I know there is a lot here but that's what I needed to make this production ready.

- fix some typings errors
- fix test not closing
- add basic cors support
- fix onAborted issue. 
- upgrade to latest uWebSockets.js
- review the whole WS part to make this optimized, and compute context while upgrade
- use the common parts that were merged from my pr to trpc (https://github.com/trpc/trpc/pull/4106)
- I let the jest/vitest things I don't know what you want to do with that, your test:coverage command does not work

### CODE REVIEW

**Comment by romanzy313** [comment]
Hello,

I have implemented most of your changes. 

But I have left out the following:
 - cors support: it can be implemented easily outside of the trpc handler, and can be fully customized by end user
 - compute context while upgrade: I want to keep internals of this adapters similar to ws implementation. In your implementation the client will never know that createContext failed, so it will attempt to reconnect to server forever

**Comment by yovanoc** [comment]
Oh great I will test your changes very soon.

I can't look at the code right now but outside cors doesnt seem to work because we need it inside the handler too, not only add an .options handler.

For the WS part, my code send a closeUpgrade, so yes, the client know, this code is already in production and that's all the changes needed to make it optimized and safe. I will compare with your version, and put some benchmarks here. Hope yours is safe and optimized enough then

**Comment by romanzy313** [comment]
Alright, thank you for taking your time to test this.

In the unit tests I have tested your `closeUpgrade` which returns 403 instead of 101. The client in this case keeps trying to reconnect to the server, as it thinks that there is an issue with the protocol. Trpc have not finalized subscription api, so its rough around the edges.

Also, I haven't tested this, but maybe you need to define OPTIONS route before trpc, so that it takes higher priority. This is exactly how it works in your handler, so why would it not work outside of it?

**Comment by yovanoc** [comment]
didn't have time to tackle this yet, but yeah you probably right for the upgrade part but might be easy to fix. But do you try to stress test your way?
For cors, you have to send the Access-Control-Allow-Origin during the post request too so we have to handle this in this package

**Comment by romanzy313** [comment]
Yes I agree, having a simple to use plugin is nice. When learning webdev I suffered with this cors thing too much.

Its possible for trpc server to add headers on each request, as can be seen [here](https://trpc.io/docs/server/caching). This is implemented internally in trpc, so I assume it works in this library. Try it out!

**Comment by romanzy313** [comment]
Closing this as all functional parts were integrated. I have also added CORS to the readme.

**Pull request closed without merging**
